name: Run Hangman Word Generator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If there are additional dependencies in a requirements.txt file, install them
          # python -m pip install -r requirements.txt

      - name: Run script
        run: |
          python generate_hangman_words.py
